<a href="https://colab.research.google.com/github/DymaStar/DTA_2026/blob/main/HW/DimaStarHW_Oksana_%22numpy_homework_ipynb%22_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [15]:
import numpy as np

# Твій код:
temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])
print("Масив:", temps)

# Атрибути — властивості масиву (без дужок!)
print("Вимірів:",   temps.ndim)    # 1 — одновимірний
print("Форма:",     temps.shape)   # (12,) — 12 елементів
print("Розмір:",    temps.size)    # 12
print("Тип даних:", temps.dtype)   # int64

# # Методи — дії над масивом (з дужками!)
print("Мінімум:",  temps.min())               # -5
print("Максимум:", temps.max())               # 23
print("Середня:",  np.round(temps.mean(), 1)) # 9.2

Масив: [-5 -4  2 10 17 21 23 22 16  9  2 -3]
Вимірів: 1
Форма: (12,)
Розмір: 12
Тип даних: int64
Мінімум: -5
Максимум: 23
Середня: 9.2


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [16]:
# Твій код:
# np.full(форма, значення)
plan = np.full((3,4), 50)

print("План:\n", plan)
print("Форма:", plan.shape)   # (3, 4)
print("Елементів:", plan.size)  # 12

# np.zeros(форма) — всі нулі
bonus = np.zeros((3, 4))
print("Бонуси:\n", bonus)

# Поелементне додавання — без циклів!
total = plan + bonus
print("Сума:\n", total)   # те саме що plan

План:
 [[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
Форма: (3, 4)
Елементів: 12
Бонуси:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Сума:
 [[50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]]


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [17]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Твій код:
# 1. Перший тиждень — індекси 0..6
week1 = sales[0:7]    # або sales[:7]
print("Тиждень 1:", week1)

# 2. Другий тиждень — індекси 7..13
week2 = sales[7:14]
print("Тиждень 2:", week2)

# 3. Вихідні — конкретні індекси списком
weekends = sales[[5,6,12,13]]
print("Вихідні:", weekends)

# 4. Через день — крок 2
every_other = sales[::2]   # 0, 2, 4, 6, 8, 10, 12
print("Через день:", every_other)

# 5. Зворотний порядок — крок -1
reversed_sales = sales[::-1]
print("Навпаки:", reversed_sales)

Тиждень 1: [320 415 290 480 350 620 580]
Тиждень 2: [310 440 305 510 370 650 595]
Вихідні: [620 580 650 595]
Через день: [320 290 350 580 440 510 650]
Навпаки: [595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [32]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Твій код:
# 1. Всі оцінки Олени — рядок 0, всі стовпці
print("Олена:", grades[0, :])    # або grades[0]

# 2. Всі оцінки з 3-го предмету — всі рядки, стовпець 2
print("Предмет 3:", grades[:, 2])

# 3. Підматриця: Максим і Аня (рядки 1-2), предмети 2-4 (стовпці 1-3)
print("Підматриця:\n", grades[1:3, 1:4])
# Результат:

# Максим: [88 74 95]
# Аня     [65 82 70]



# 4. Останній студент, останній предмет
print("Богдан, предмет 5:", grades[-1, -1])   # 79

Олена: [85 72 91 78 88]
Предмет 3: [91 74 82 68]
Підматриця:
 [[88 74 95]
 [65 82 70]]
Богдан, предмет 5: 79


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [33]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Твій код:

# 1. Переводимо в гривні — множимо ВЕСЬ масив на курс
kurs = 41.5
prices_uah = np.round(prices_usd * kurs, 2)
print("Ціни в грн:", prices_uah)

# 2. Додаємо ПДВ 20% — множимо на 1.2
prices_vat = np.round(prices_uah * 1.2, 2)
print("З ПДВ:", prices_vat)

# 3. Статистика
print("Мінімум:",  prices_vat.min())
print("Максимум:", prices_vat.max())
print("Середня:",  np.round(prices_vat.mean(), 2))

# 4. Загальна сума кошика
print("Всього:", np.round(prices_vat.sum(), 2))

Ціни в грн: [ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]
З ПДВ: [ 796.3  2116.5   398.4  6225.   1680.74 3346.56  497.5 ]
Мінімум: 398.4
Максимум: 6225.0
Середня: 2151.57
Всього: 15061.0


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [20]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:
# 1. Вартість кожного товару = кількість × ціна
total_each = quantity * cost_each
print("Вартість кожного:", total_each)
# [30000, 81000, 13500, 171000, 28500, 24000, 45000]

# 2. Загальна вартість складу
print("Всього на складі:", total_each.sum())

# 3. Товар з найбільшою вартістю
idx_max = np.argmax(total_each)      # повертає ІНДЕКС, не значення
print("Найдорожчий:", names[idx_max], "—", total_each[idx_max])

# 4. Товар з найменшою вартістю
idx_min = np.argmin(total_each)
print("Найдешевший:", names[idx_min], "-", total_each[idx_min])
# 5. Середня вартість одного найменування
print("Середня:", np.round(total_each.mean(), 2))

Вартість кожного: [ 30000  81000  13500 171000  28500  24000  45000]
Всього на складі: 393000
Найдорожчий: Монітор — 171000
Найдешевший: Зошит - 13500
Середня: 56142.86


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [21]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:
# 1-2. Маски для вчасних і запізнілих
on_time = delivery_time <= 30   # булева маска
late   = delivery_time > 30

# Самі значення через фільтрацію
on_time_vals = delivery_time[on_time]
late_vals    = delivery_time[late]
print("Вчасні:", on_time_vals)
print("Запізнілі:", late_vals)

# 3. Кількість — sum() рахує True як 1
print("Вчасних:", on_time.sum())
print("Запізнілих:", late.sum())

# 4. Відсоток запізнілих
pct = np.round(late.sum() / len(delivery_time) * 100 , 1)
print("Відсоток запізнілих:", pct, "%")

# 5. Середня затримка серед запізнілих
delays = late_vals - 30           # [5, 11, 25, 3, 18, 22, 8, 14, 6]
print(np.round(delays.mean(), 1)) # 12.4 хв — ось реальна середня затримка

Вчасні: [22 28 19 27 24 26 18 29 23 20]
Запізнілі: [35 41 55 33 48 31 52 38 44 36]
Вчасних: 10
Запізнілих: 10
Відсоток запізнілих: 50.0 %
11.3


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [22]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Твій код:
# 1. Середнє за місяць
avg = daily.mean()
print("Середнє:", np.round(avg, 1))

# 2. Дні вище середнього
above_avg = daily[daily > avg]
print("Днів вище середнього:", len(above_avg))

# 3. np.where — як if/else для цілого масиву
status = np.where(daily > avg, "Гарний день", "Звичайний день")

# 4. Перші 10 днів
for i in range(10):
    print(f"День {i+1}: {daily[i]} — {status[i]}")

Середнє: 434.2
Днів вище середнього: 14
День 1: 202 — Звичайний день
День 2: 535 — Гарний день
День 3: 370 — Звичайний день
День 4: 206 — Звичайний день
День 5: 171 — Звичайний день
День 6: 800 — Гарний день
День 7: 120 — Звичайний день
День 8: 714 — Гарний день
День 9: 221 — Звичайний день
День 10: 566 — Гарний день


---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [23]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:
# 1. Перетворюємо 24 елементи → матриця 6×4
matrix = hourly.reshape(6, 4)
print("Матриця 6x4:\n", matrix)

# 2. Сума по рядках (кожен 4-годинний блок)
block_sums = matrix.sum(axis=1)
print("Сума кожного блоку:", block_sums)

# 3. Відсортований масив
sorted_hourly = np.sort(hourly)
print("Відсортовано:", sorted_hourly)

# 4. Індекси в порядку зростання
sorted_indices = np.argsort(hourly)
print("Індекси:", sorted_indices)

# 5. Топ-3 години — останні 3 індекси (найбільші)
top3 = sorted_indices[-3:]
print("Топ-3 години:", top3)

Матриця 6x4:
 [[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]
Сума кожного блоку: [ 28  66 235 240 257 112]
Відсортовано: [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]
Індекси: [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]
Топ-3 години: [19 12 18]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [24]:
# Твій код:
np.random.seed(99)

# Вік 50 клієнтів: цілі від 18 до 65
# randint(low, high) → high НЕ включно → пишемо 66
ages = np.random.randint(18, 66, size=50)

# Оцінки задоволеності: нормальний розподіл
scores_raw = np.random.normal(7, 1.5, size=50)
scores = np.round(np.clip(scores_raw, 1, 10), 1)  # обрізаємо і округляємо

print("Середній вік:", np.round(ages.mean(), 1))
print("Середня оцінка:", np.round(scores.mean(), 1))

# Задоволені — оцінка >= 8
satisfied = (scores >= 8).sum()
print("Задоволених:", satisfied)
print("Відсоток:", np.round(satisfied / len(scores) * 100, 1), "%")

Середній вік: 41.8
Середня оцінка: 6.9
Задоволених: 10
Відсоток: 20.0 %


---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [25]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [26]:
# Твій код:
np.random.seed(2024)
base = np.random.randint(200, 800, 56)
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print("Загальна виручка:", sales_56.sum())
print("Середньоденна:", np.round(sales_56.mean(), 2))
print("Мінімум:", sales_56.min())
print("Максимум:", sales_56.max())
print("Стандартне відхилення:", np.round(sales_56.std(), 2))

Загальна виручка: 31819
Середньоденна: 568.2
Мінімум: 222
Максимум: 1072
Стандартне відхилення: 195.52


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [27]:
# Твій код:
# Перетворюємо 56 днів → матриця 8×7
weekly = sales_56.reshape(8, 7)

# Виручка кожного тижня — сума по рядках
week_totals = weekly.sum(axis=1)
print("По тижнях:", week_totals)

# Найкращий тиждень
best_week = np.argmax(week_totals)
print(f"Найкращий тиждень: {best_week+1} — {week_totals[best_week]} грн")

# Середнє по днях тижня — середнє по стовпцях
day_avg = weekly.mean(axis=0)
days = ["Пн","Вт","Ср","Чт","Пт","Сб","Нд"]
best_day = np.argmax(day_avg)
print(f"Найприбутковіший день: {days[best_day]}")

По тижнях: [4555 3921 3563 3546 5036 3300 4228 3670]
Найкращий тиждень: 5 — 5036 грн
Найприбутковіший день: Нд


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [28]:
# Твій код:
# Слабкі і сильні дні
weak   = sales_56 < 400
strong = sales_56 > 700

print("Слабких днів:", weak.sum())
print("Сильних днів:", strong.sum())
print("Середня у слабкі:", np.round(sales_56[weak].mean(), 2))
print("Середня у сильні:", np.round(sales_56[strong].mean(), 2))

# Вкладений np.where для трьох категорій
labels = np.where(sales_56 < 400, "Слабкий",
         np.where(sales_56 > 700, "Сильний", "Нормальний"))

# Перші 14 днів
for i in range(14):
    print(f"День {i+1:2}: {sales_56[i]} — {labels[i]}")

Слабких днів: 12
Сильних днів: 19
Середня у слабкі: 302.0
Середня у сильні: 785.16
День  1: 706 — Сильний
День  2: 739 — Сильний
День  3: 748 — Сильний
День  4: 646 — Нормальний
День  5: 383 — Слабкий
День  6: 556 — Нормальний
День  7: 777 — Сильний
День  8: 427 — Нормальний
День  9: 274 — Слабкий
День 10: 522 — Нормальний
День 11: 680 — Нормальний
День 12: 708 — Сильний
День 13: 465 — Нормальний
День 14: 845 — Сильний


---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
